### ISSUE TITLE
Не существующие ученики в списке учеников xD.

### ISSUE THREAD

**Issue by Xefise** [Senteris/DKControl#5]
В тестовой DB
Ну возможно это что-то другое
![browser_8Fsaa1W3jW](https://user-images.githubusercontent.com/45072628/96353142-1cf61d00-10d2-11eb-9800-c0768b7887be.png)
![browser_3PurnM4fUG](https://user-images.githubusercontent.com/45072628/96353144-1ebfe080-10d2-11eb-9a81-e50d7e668bb1.png)

**Comment by Xefise** [comment]
Ещё у http://127.0.0.1:8000/students/17/ есть родитель, у которого детё StudentMore object (15)

**Comment by Neisvestney** [comment]
Fix in https://github.com/Senteris/DKControl/commit/b7ae517f8ee564e48ec51e6ee0eb2d392080065d

**Comment by Xefise** [comment]
Fixed at 433d6d4
